#!/usr/bin/env python
# -*- coding: utf-8 -*-

"""Console script for datavault."""

import click
import logging

import sys
import re

from datavault.datavault import DataVault


def setup_logging():
    root_logger = logging.getLogger()
    root_logger.setLevel(logging.DEBUG)
    console_handler = logging.StreamHandler()
    log_level = logging.DEBUG

    formatter = logging.Formatter('%(asctime)s [%(levelname)s] (%(name)s) %(message)s')
    console_handler.setFormatter(formatter)
    console_handler.setLevel(log_level)
    root_logger.addHandler(console_handler)


@click.command()
@click.argument('port')
@click.argument('password', default='admin')
def main(port, password):
    """Console script for datavault."""
    setup_logging()

    try:
        port = int(port)
    except:
        sys.exit(255)

    if port < 1024 or port > 65535:
        sys.exit(255)

    if sys.argv[1].startswith('0') or sys.argv[1].startswith(' ') or sys.argv[1].endswith(' '):
        sys.exit(255)

    if len(sys.argv) > 2:
        matcher = re.compile('[A-Za-z0-9_ ,;\.?!-]*')
        if not matcher.match(str(sys.argv[2])):
            sys.exit(255)

    vault = DataVault(port=port, admin_password=password)

    try:
        vault.start()
    except KeyboardInterrupt:
        vault.stop()


if __name__ == "__main__":
    main()
